# use java support.
language: java

# required to install tools on Linux
sudo: required

# skip install
install: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"

env:
  - secure: "v5zpVQPtKFqONZiilloJ7gI4c6I25rObDYUHssht48vIIQR3ivWULdApP5JBCqokevWHf4AgSKub1PY97QADxtEWNLvXyTHbXjwXLS6fNXLhSlqRCuVFn/YHGH4yNA/B+6Cd14pEeLnd1tvkuFbIgkOyDe9vl3USw1tDmiwopPNujIzJXJBwMMn7HwzNIjNiTFVKOMPUHI6uG2ehgkz/EXwz9gwyV0wjR8uZxRXAF5NMGq+qfvjGz0bw04rLkgOFd7q0+IpG8whxWHvnQkD1Zgla2DyIaYiVUL23swNz5F0gNBt4YMMlK1mQ08CxLWkPkLMox34GOTExMlE58PWgxHo7hKHk6tAQ4uG+u/2pal+Dpi98qwKtmyIq+WjXpRx/NxFbFAy1Q4jQ5i5UNDUd615cmPkwhaU8DAICu7Aup10DP+OUoncSmBasybFff9D6DV6t7HYQwlvFI2TC+WpGaJDhA1JkknT48qGQVZqxJfCzLxy6HYeIpaq+IGdGWJlWPBDFzL0nJvOlKTeo6+IKANPhCR5cs6sgbTfZ6US8D/X2mbqldUidYH9TyY+8oKafpxwLdu7Q48GUpty76C3gGSLqM9Etbuoc4xnCn1xKlinifHPLFAq5OPR/KJe5ExCuulTZz3NTVRfW4coqCk7KxkLLxdkPV8ai1B1zqTY/znA="
  - secure: "CSYItVKlnNvO1iGD7XrP4nyBEK/DZbluzCbbYiXxxvZ9fzklLizBfRLS8vVO7C+Dvz5JP1/8UTm5i0LdjSY6jXm1UMhaaPStZvxroQSZnKkE7gQ1jdph2JJSyNVRxdRUO6xw/wwDG6xszlVMa2x92jMFU1jFXUG3oc06ogQ71oRrVVhVuQLXTTgfNzaO3r/c4bhf7dn984iVZ2LIpZcCngOSfKdQ6WmwpzngMewyiq9CGpsZNtJ3Rtlvd0yq7EJbalB5PG7/nyCNMEIdLphKp9rzwNWI4R2ZIJC19g7g6+OZvxIgSPSOvz0qOsCo5knPENDRrnmO9EUZvF5M5JnW3/manXQCHSH9OPQslqBSyWLBPX/Pc4ZqJzCvdnSxjBiGngs6NPSmgfiF1VEs727N8dZCs3YGfnbIj7D0zByGu5KAChpVrET+i9ewEyjJMw/aqSNNMXYiFJ0jKoGQgIDkwynxMpxmOKqvf9Y7i+afWzAzQqErhdJKAyAvxMSEFik/RxGmyzOSlSDQ1JfLoW4Ugmpg0gukJ1z3NNNyms5cf2+0CYH403pNACuJJWUh6jH603W9HYg15Ii7qIiJymZpSxDSTiqVv5GH72qDcV63wH5ALLoTMReXGxnNiH7JK3Jhkod5AZy+VV6CyL8LoX1JRZSm1NtnI2YLKLmn58ROpao="

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode9

# configure xvfb screen on linux 
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    openssl aes-256-cbc -k "$ENC_SECRET" -in app/assets/osx/codesign.cer.enc -out app/assets/osx/codesign.cer -d;
    openssl aes-256-cbc -k "$ENC_SECRET" -in app/assets/osx/codesign.p12.enc -out app/assets/osx/codesign.p12 -d;
    fi

script:
  - chmod +x .ci/build.sh;
  - sh .ci/build.sh;
            
deploy:
  provider: releases
  api_key:
    secure: "GdeRIB3FdguSiVIueE0N+y3D3+XE4wY9OCYnW13l0DxZxQuK9nTVl668Hek7w+jcmnYbaQ5Zn1Fl8H2Elx4uJnd6QOCFlPzaXdQoVtmKLYh95yLmECdsONHFdZmejIl5yk2c+D+Ln0/MXojo0wEW1356mPA10ixDfD2wVtrKgKcC2evH5d7vAMuOOUhBW18Y/kL7ZjYHkfj1kM0r1zczId2lELBYrURcexD3yoolSyfm6D7D/k1XY24INFT6bCGkzyp39npiIPpqhh6fSr0ljVBAn8ZUwcIpH09LK0pfJJxg4ZVb8G2l3yjo4TAmJwJFlKDyQY2NDQIDO11keJMBTqMwblSW6gKo8tApBsGeVNMoyMVw1vy0hyMPB6+NQPHuZPR2neSh8qx3o2NB+RFLn/WF6rKHtEfUxdU1kcwDLjsc35qEhz95/a2cbHkbIl4n0kDoNUlmwQULA97oICMoOeD/3Lqv+8RixE2OcqUOV224zOZp4FpPAYr36t4UZHSXQMYHE/k5tvlcENz/GOrHCs1wQOKBD040Wz7I/1k+zhS9jMaYMefNhj/l9tBmp/9CC6kn3HyG+APFl3cgSQNFhFaL0gmpRcDMsorDEo0pHibkCyoHNtXkZpWZBVxo14PfPOEClNn32ewIuuQrCYHStFXTZB8S1thcexnyXSw/OmU="
  file: 
    - "dist/bundles/SceneBuilder-${TRAVIS_TAG}.deb"
    - "dist/bundles/SceneBuilder-${TRAVIS_TAG}.rpm"
    - "dist/bundles/SceneBuilder-${TRAVIS_TAG}.dmg"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: gluonhq/scenebuilder
