# build version
version: '{build}'

# environment settings
environment:
  enc_secret:
    secure: o6Q0m990l/iQj1I/x/pqSxfHZonlC0NyCFACVv37Pw8=
  key_secret:
    secure: 2XAgf/3HBGETiEIToJOB7A==
  signtool: C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    
# install required tools
install:
  - cmd: echo %JAVA_HOME%
  - cmd: choco install -y InnoSetup
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt app\assets\windows\code-sign.p12.enc -secret %enc_secret%
  - sh: ./appveyor-tools/secure-file -decrypt app/assets/windows/code-sign.p12.enc -secret $enc_secret

# build and install artifacts
build_script:
  - cmd: .ci\build.bat

artifacts:
  - path: dist\bundles\SceneBuilder-%APPVEYOR_REPO_TAG_NAME%.exe
    name: windows-scenebuilder

deploy:
  - provider: GitHub
    name: production
    auth_token:
        secure: 90W2MMGEXPRS62tHmCQn1lhJhYnM1yQ754ssBft0pSAe0Go1sFDZQ3Jp5JusSIxF
    artifact: windows-scenebuilder
    on:
      appveyor_repo_tag: true
